name: Test
on:
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
    working-directory: api
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: ls
      - run: npm ci
      - run: npx cloud test
